# -*- mode: python ; coding: utf-8 -*-
"""Cross-platform PyInstaller spec for the AnythingToMarkdown desktop app.

Output depends on the platform and two environment switches:

    (default on macOS)   dist/AnythingToMarkdown.app       .app bundle
    (default elsewhere)  dist/AnythingToMarkdown[.exe]     single file
    BUILD_ONEDIR=1       dist/AnythingToMarkdown/          one folder
    FORCE_ONEFILE=1      single file even on macOS

BUILD_ONEDIR is what the MSIX package is built from: an MSIX ships an already
unpacked app, so the one-file bootloader's extract-to-temp step would only
add startup cost (and Store certification frowns on it).

Build with:
    macOS/Linux:  .venv/bin/pyinstaller packaging/AnythingToMarkdown.spec --noconfirm
    Windows:      .venv\\Scripts\\pyinstaller packaging\\AnythingToMarkdown.spec --noconfirm
"""

import os
import sys

from PyInstaller.utils.hooks import collect_all, collect_submodules

# Keep the bundle version in step with anytomd.__version__ (the single source
# of truth) instead of hard-coding it here. SPECPATH is injected by PyInstaller.
sys.path.insert(0, SPECPATH)
try:
    from version_tool import read_version
    APP_VERSION = read_version()
except Exception:
    APP_VERSION = "0.0.0"

IS_MAC = sys.platform == "darwin"
IS_WIN = sys.platform == "win32"

# Platform-appropriate icon (generated by packaging/make_icon.py).
if IS_MAC:
    ICON = "AppIcon.icns"
elif IS_WIN:
    ICON = "AppIcon.ico"
else:
    ICON = None

# Optional macOS code signing (used by `make notarize`). When the identity env
# var is unset, the app is built unsigned exactly as before.
CODESIGN_IDENTITY = os.environ.get("MACOS_CODESIGN_IDENTITY") or None
ENTITLEMENTS = os.environ.get("MACOS_ENTITLEMENTS") or None

# macOS ships a proper .app bundle; Windows/Linux ship a single-file executable.
# Set FORCE_ONEFILE=1 to produce a single-file binary on macOS too (mainly for
# testing the onefile path), or BUILD_ONEDIR=1 for the unpacked folder layout
# the MSIX package needs.
BUILD_APP = IS_MAC and os.environ.get("FORCE_ONEFILE") != "1"
BUILD_ONEDIR = os.environ.get("BUILD_ONEDIR") == "1"

datas, binaries, hiddenimports = [], [], []

# MarkItDown discovers its converters through package metadata / entry points,
# and several optional deps load lazily — collect them wholesale so nothing is
# missing at runtime.
for pkg in (
    "markitdown",   # core + built-in converter entry points
    "magika",       # file-type detection model data files (easily missed)
):
    d, b, h = collect_all(pkg)
    datas += d
    binaries += b
    hiddenimports += h

# Office / document parsers that MarkItDown imports lazily by name.
for pkg in (
    "pdfminer",
    "mammoth",
    "openpyxl",
    "pptx",
    "xlrd",
    "bs4",
    "markdownify",
    "charset_normalizer",
):
    try:
        hiddenimports += collect_submodules(pkg)
    except Exception:
        pass


a = Analysis(
    ["app_entry.py"],
    pathex=[".."],
    binaries=binaries,
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=[],
    runtime_hooks=[],
    excludes=["reportlab", "docx"],  # test-only generators, never needed at runtime
    noarchive=False,
)

pyz = PYZ(a.pure)

# Packaging mode:
#   * macOS  -> one-folder build wrapped in a proper .app bundle (fast launch,
#     real icon/Finder integration, notarizable). The .dmg ships this.
#   * BUILD_ONEDIR=1 -> the same one-folder layout without the .app wrapper;
#     this is the payload the MSIX package is built from.
#   * Windows/Linux default -> a single self-contained executable (onefile) so
#     there's just one file to hand someone.
if BUILD_APP or BUILD_ONEDIR:
    exe = EXE(
        pyz,
        a.scripts,
        [],
        exclude_binaries=True,
        name="AnythingToMarkdown",
        debug=False,
        bootloader_ignore_signals=False,
        strip=False,
        upx=False,
        console=False,            # windowed app (no terminal)
        disable_windowed_traceback=False,
        # Finder passes "Open With" files as argv; macOS-only PyInstaller feature.
        argv_emulation=BUILD_APP,
        target_arch=None,
        codesign_identity=CODESIGN_IDENTITY if BUILD_APP else None,
        entitlements_file=ENTITLEMENTS if BUILD_APP else None,
        icon=ICON,
    )
    coll = COLLECT(
        exe,
        a.binaries,
        a.datas,
        strip=False,
        upx=False,
        upx_exclude=[],
        name="AnythingToMarkdown",
    )

if BUILD_APP:
    app = BUNDLE(
        coll,
        name="AnythingToMarkdown.app",
        icon=ICON,
        bundle_identifier="org.padakhep.anythingtomarkdown",
        info_plist={
            "CFBundleName": "AnythingToMarkdown",
            "CFBundleDisplayName": "AnythingToMarkdown",
            "CFBundleShortVersionString": APP_VERSION,
            "CFBundleVersion": APP_VERSION,
            "NSHighResolutionCapable": True,
            "LSMinimumSystemVersion": "11.0",
            # Allow the app to receive files dropped onto its Dock/Finder icon.
            "CFBundleDocumentTypes": [
                {
                    "CFBundleTypeName": "Document",
                    "LSItemContentTypes": [
                        "com.adobe.pdf",
                        "org.openxmlformats.wordprocessingml.document",
                        "org.openxmlformats.presentationml.presentation",
                        "org.openxmlformats.spreadsheetml.sheet",
                        "public.html",
                        "public.comma-separated-values-text",
                        "public.json",
                        "public.xml",
                        "public.plain-text",
                    ],
                    "CFBundleTypeRole": "Viewer",
                    "LSHandlerRank": "Alternate",
                }
            ],
        },
    )
elif not BUILD_ONEDIR:
    # Single-file executable: bundle scripts + binaries + datas into one EXE.
    exe = EXE(
        pyz,
        a.scripts,
        a.binaries,
        a.datas,
        [],
        name="AnythingToMarkdown",
        debug=False,
        bootloader_ignore_signals=False,
        strip=False,
        upx=False,
        runtime_tmpdir=None,
        console=False,            # windowed app (no terminal)
        disable_windowed_traceback=False,
        argv_emulation=False,
        target_arch=None,
        codesign_identity=None,
        entitlements_file=None,
        icon=ICON,
    )
