# -*- mode: python ; coding: utf-8 -*-
"""Cross-platform PyInstaller spec for the AnythingToMarkdown desktop app.

On macOS it produces AnythingToMarkdown.app; on Windows/Linux it produces a
one-folder app (dist/AnythingToMarkdown/AnythingToMarkdown[.exe]).

Build with:
    macOS/Linux:  .venv/bin/pyinstaller packaging/AnythingToMarkdown.spec --noconfirm
    Windows:      .venv\\Scripts\\pyinstaller packaging\\AnythingToMarkdown.spec --noconfirm
"""

import os
import sys

from PyInstaller.utils.hooks import collect_all, collect_submodules

IS_MAC = sys.platform == "darwin"
IS_WIN = sys.platform == "win32"

# Platform-appropriate icon (generated by packaging/make_icon.py).
if IS_MAC:
    ICON = "AppIcon.icns"
elif IS_WIN:
    ICON = "AppIcon.ico"
else:
    ICON = None

# Optional macOS code signing (used by `make notarize`). When the identity env
# var is unset, the app is built unsigned exactly as before.
CODESIGN_IDENTITY = os.environ.get("MACOS_CODESIGN_IDENTITY") or None
ENTITLEMENTS = os.environ.get("MACOS_ENTITLEMENTS") or None

datas, binaries, hiddenimports = [], [], []

# MarkItDown discovers its converters through package metadata / entry points,
# and several optional deps load lazily — collect them wholesale so nothing is
# missing at runtime.
for pkg in (
    "markitdown",   # core + built-in converter entry points
    "magika",       # file-type detection model data files (easily missed)
):
    d, b, h = collect_all(pkg)
    datas += d
    binaries += b
    hiddenimports += h

# Office / document parsers that MarkItDown imports lazily by name.
for pkg in (
    "pdfminer",
    "mammoth",
    "openpyxl",
    "pptx",
    "xlrd",
    "bs4",
    "markdownify",
    "charset_normalizer",
):
    try:
        hiddenimports += collect_submodules(pkg)
    except Exception:
        pass


a = Analysis(
    ["app_entry.py"],
    pathex=[".."],
    binaries=binaries,
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=[],
    runtime_hooks=[],
    excludes=["reportlab", "docx"],  # test-only generators, never needed at runtime
    noarchive=False,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name="AnythingToMarkdown",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    console=False,            # windowed app (no terminal)
    disable_windowed_traceback=False,
    argv_emulation=IS_MAC,    # macOS-only: lets Finder "Open With" pass files as argv
    target_arch=None,
    codesign_identity=CODESIGN_IDENTITY,
    entitlements_file=ENTITLEMENTS,
    icon=ICON,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=False,
    upx_exclude=[],
    name="AnythingToMarkdown",
)

# Wrap the one-folder app in a clickable .app bundle on macOS only.
if IS_MAC:
    app = BUNDLE(
        coll,
        name="AnythingToMarkdown.app",
        icon=ICON,
        bundle_identifier="org.padakhep.anythingtomarkdown",
        info_plist={
        "CFBundleName": "AnythingToMarkdown",
        "CFBundleDisplayName": "AnythingToMarkdown",
        "CFBundleShortVersionString": "1.0.0",
        "CFBundleVersion": "1.0.0",
        "NSHighResolutionCapable": True,
        "LSMinimumSystemVersion": "11.0",
        # Allow the app to receive files dropped onto its Dock/Finder icon.
        "CFBundleDocumentTypes": [
            {
                "CFBundleTypeName": "Document",
                "LSItemContentTypes": [
                    "com.adobe.pdf",
                    "org.openxmlformats.wordprocessingml.document",
                    "org.openxmlformats.presentationml.presentation",
                    "org.openxmlformats.spreadsheetml.sheet",
                    "public.html",
                    "public.comma-separated-values-text",
                    "public.json",
                    "public.xml",
                    "public.plain-text",
                ],
                "CFBundleTypeRole": "Viewer",
                "LSHandlerRank": "Alternate",
            }
        ],
    },
)
